output_enabled:
- blender
- gazebo
output:
  blender:
    type: blender_file
    filename: bean_field_09.blend
  gazebo:
    type: gazebo_model
    name: bean_field_09
    path: .
field:
  headland_width: 2.2
  random_seed: 1188332531
  beds:
    bed1:
      plant_type: bean
      plant_height: 0.192
      height_tolerance_coeff: 0.15
      row_distance: 0.688
      rows_count: 6
      plants_count: 70
      plant_distance: 0.263
      bed_width: 4.13
      orientation: zero
  noise:
    position: 0.016
    tilt: 0.08
    missing: 0.194
    scale: 0.107
  weeds:
    portulaca:
      plant_type: portulaca
      density: 6.7
      distance_min: 0.189
      max_height: 0.057
      noise_scale: 0.263
      noise_offset: 0.134
  stones:
    density: 53.4
    distance_min: 0.055
    noise_scale: 0.25
    noise_offset: 0.232
render:
  directory: render
  frames: 100
  samples: 12
  resolution_x: 640
  resolution_y: 480
  env_rotation_deg: 152.5
  camera:
    height: 0.91
    fov_deg: 70.0
    roll_deg: 0.0
    pitch_deg: 0.0
    yaw_deg: 0.0
    y_jitter: 0.4
  label_colors:
    crop:
    - 0
    - 255
    - 0
    weed:
    - 255
    - 0
    - 0
    background:
    - 0
    - 0
    - 0
